In [1]:
import os
import numpy

In [14]:
from hw3_jacquilyn_support_functions import square

In [17]:
#Problem 2

#part h
print("Problem 2 Part h")

test_square_1= list(range(10))

print(square(test_square_1))


#part i
print("\nProblem 2 Part i")

test_square_2= numpy.arange(25).reshape(5,5)

print(square(test_square_2))

Problem 2 Part h
[ 0  1  4  9 16 25 36 49 64 81]

Problem 2 Part i
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]
